### ISSUE TITLE
Fix return type for instantMeiliSearch

### ISSUE THREAD

**Issue by shtbik** [meilisearch/meilisearch-react#19]
**Description**
Following the official React SDK [tutorial](https://github.com/meilisearch/meilisearch-react) I've got the type definition error when called `instantMeiliSearch()`.

`const searchClient = instantMeiliSearch(process.env.NEXT_PUBLIC_SEARCH_URL, process.env.NEXT_PUBLIC_SEARCH_KEY)`

**Expected behavior**
Return type should be fixed

**Current behavior**
I've got the type definition error

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/12717213/137848530-e4e0b391-f91d-4da1-8221-bbe31fc0c44a.png)

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- `"@meilisearch/instant-meilisearch": "0.5.6"`
- `"react-instantsearch-dom": "6.12.1"`
- `"react": "17.0.2"`
- `TypeScript Version 4.4.3`

There is no type error for `meilisearch` package
```
const searchClient = new MeiliSearch({
  host: process.env.NEXT_PUBLIC_SEARCH_URL,
  apiKey: process.env.NEXT_PUBLIC_SEARCH_KEY,
})
```

P.S.
When I was going through the [guide](https://docs.meilisearch.com/learn/what_is_meilisearch/sdks.html) I felt that there are a bunch of libraries and hard to understand what do you exactly need to start, what is the difference between them.

https://github.com/meilisearch/meilisearch-js
https://github.com/meilisearch/meilisearch-react
https://github.com/meilisearch/instant-meilisearch
https://github.com/algolia/react-instantsearch

Thank you for your effort! Feel free to ask for any other details.

**Comment by bidoubiwa** [comment]
Hello @shtbik ! Indeed this error is weird as I've checked the type definition and it is as follow:

```ts
function instantMeiliSearch(
  hostUrl: string,
  apiKey = '',
  options: InstantMeiliSearchOptions = {}
): InstantMeiliSearchInstance
```

Where `InstantMeiliSearchInstance` is declared like this: 
```ts
export type InstantMeiliSearchInstance = SearchClient & {
  MeiliSearchClient: MeiliSearch
}
```

and this is the type definition when I hover on it: 

<img width="851" alt="Screenshot 2021-10-19 at 14 09 35" src="https://user-images.githubusercontent.com/33010418/137906455-c688028b-0e6d-456e-b706-02bfa8183a02.png">

**Comment by bidoubiwa** [comment]
Hello @shtbik 
The `SearchClient` type is actually available only if you also have another package from algolia. You need to add [algoliasearch](https://github.com/algolia/algoliasearch-client-javascript) as a dev dependency of your project to be able to get access to the SearchClient type.

**Comment by bidoubiwa** [comment]
I suppose this is resolved, don't hesitate to tell otherwise if it isn't. Normally `instant-meilisearch` now ships with `instantsearch.js` types definitions
