### ISSUE TITLE
RefinementList: what kind of data type the attribute requires?

### ISSUE THREAD

**Issue by edpomacedo** [meilisearch/meilisearch-react#25]
Hi there! Thank you all, meilisearch is awesome!

I'm figuring it out from the CodeSandbox example with the steam-video-games index. I actually built my own index with strapi, but I can't make the RefinementList work. It returns blank...

The RefinementList must be a string? Could it be an array? Does it requires some kind of relation?

**Comment by bidoubiwa** [comment]
Hey! Are there logs appearing in the [console of your browser](https://balsamiq.com/support/faqs/browserconsole) (my bad if this is useless it is just in case)? The must common error with refinementList is not adding the attribute to the [`filterableAttributes` list](https://docs.meilisearch.com/learn/configuration/settings.html#filterable-attributes). 
Here is some explaination in [instant-meilisearch case](https://github.com/meilisearch/instant-meilisearch/#hierarchical-menu-usage).

**Comment by bidoubiwa** [comment]
I'm closing this issue. If your issue is not fixed please tell so :)
