### ISSUE TITLE
Configure widget is broken

### ISSUE THREAD

**Issue by Snailed** [meilisearch/meilisearch-react#3]
The `Configure` widget does not have any effect on search results. This means that it is impossible to use filtering and specify the amount of hits per page.

Code example:
https://codesandbox.io/s/ms-react-is-forked-i8fiw?file=/src/App.js

**Comment by curquiza** [comment]
Hello @Snailed!
Sorry for the delay!

Did you try to use `Configure` for the filters? It indeed did not work before, a fixed has just been done. The release with the fix is out, see the [v0.2.1](https://github.com/meilisearch/instant-meilisearch/releases/tag/v0.2.1).
Tell me if it fixes your issue!

**Comment by curquiza** [comment]
Closing this issue since there is no more update. Feel free to re-open if needed.
