### ISSUE TITLE
Input broken caused with React Strict Mode

### ISSUE THREAD

**Issue by konhi** [meilisearch/meilisearch-react#30]
#### Description

Algolia's `react-instantsearch` is incompatible with [React Strict Mode](https://reactjs.org/docs/strict-mode.html). It causes input to be unusable. **It's not caused by Meilisearch dependencies.**

I'm reporting this issue in case someone stumbles with this problem as it might often happen.

#### Related Issues
- https://github.com/algolia/react-instantsearch/issues/1743
- https://github.com/algolia/react-instantsearch/issues/3537
- https://github.com/algolia/instantsearch.js/issues/5241

#### Temporary solution
1. disable React Strict Mode

**or**

2. use [react-instantsearch-hooks](https://www.npmjs.com/package/react-instantsearch-hooks) instead of [react-instantsearch-dom](https://www.npmjs.com/package/react-instantsearch-dom). This approach seems to be [recommended by Algolia!](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react-hooks/#difference-with-react-instantsearch)
![image](https://user-images.githubusercontent.com/61631665/177158969-ce38d576-3a03-46ef-8dc0-59941028b537.png)

**Comment by bidoubiwa** [comment]
Thanks a lot for this information!

**Comment by Smartmind12** [comment]
@bidoubiwa I would like to work on this issue to document it...Kindly issue it to me as part of "Hacktoberfest" !

**Comment by bidoubiwa** [comment]
Hey @Smartmind12 ! 
This is not an issue but documentation for users that might stumble upon the same problem.

**Comment by Smartmind12** [comment]
> Hey @Smartmind12 !
> This is not an issue but documentation for users that might stumble upon the same problem.

I understand thanks alot! I would suggest to document it in the docs as a “Note” section under Instant Search, for better reachability!! 

Let me know if i can help in the documentation of it.

**Comment by bidoubiwa** [comment]
Hey @Smartmind12, since this is an issue only at `instantsearch` side, I'm avoiding documenting their bugs. If tomorrow they fix it I might not realize it and thus leave outdated documentation on this README.md. We should even consider closing this issue here.

**Comment by bidoubiwa** [comment]
Feel free to re-open the issue if the problem persists!
