### ISSUE TITLE
Consider Support Of A New React Meilisearch Package

### ISSUE THREAD

**Issue by ItamarSmirra** [meilisearch/meilisearch-react#31]
**Description**
I have recently created a new React client package to integrate with a Meilisearch server called [react-meilisearch](https://www.npmjs.com/package/react-meilisearch) . It has some nice and helpful React hooks for smoothly integration with Meilisearch.

I have created it because I personally prefer React hooks over predesigned and predefined components, like [react-instantsearch](https://github.com/algolia/react-instantsearch/) has. It gives me better control of my code, and I am sure I am not alone here.

You should take a look at my new package and consider maybe suggest it also as a valid solution for React integration with meilisearch, I promise it will worth your time.

**Basic example**
The basic use case example goes like this:
```javascript
import { useSearch } from 'react-meilisearch';
const { loading, error, data } = useSearch({ index: 'movies', query: 'Comedy' });
```
For more details please take a look at me README file, it has several examples and explanations.

If you have any suggestions or ideas please let me know and I will work on it.
Thank you!

**Comment by bidoubiwa** [comment]
Closing this, thanks again 🙏
