### ISSUE TITLE
Can I use react-instantsearch-hooks-web with Meilisearch?

### ISSUE THREAD

**Issue by Vashiru** [meilisearch/meilisearch-react#34]
I'm reading the documentation of InstantSearch in order to implement `meilisearch-react` and I notice:

"We released [React InstantSearch Hooks](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react-hooks/), a new InstantSearch library for React. We recommend [using React InstantSearch Hooks](https://www.algolia.com/doc/guides/building-search-ui/getting-started/react-hooks/) in new projects or [upgrading from React InstantSearch](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react-hooks/)."

Along with:

"React InstantSearch and React InstantSearch Hooks aren’t compatible. You can’t use the Hooks provided by React InstantSearch Hooks with the React InstantSearch components."

Seeing that `meilisearch-react` makes use of `react-instantsearch-dom`, I figure that it's still using the older InstantSearch implementation rather than the hooks implementation.

Can I already seafely use react-instantsearch-hooks-web, or will that give me compatiblity issues with Meilisearch?

**Comment by bidoubiwa** [comment]
Since meilisearch-react is only a repo showcasing instant-meilisearch in a react environment, there should be no reason it does not work. 
I tried it locally and it works :)

**Comment by bidoubiwa** [comment]
Hey @Vashiru, I'm closing this issue as I suppose that it is solved. 
Please re-open it if it does not!
