### ISSUE TITLE
`_snippetResult` is null

### ISSUE THREAD

**Issue by Shriram-Balaji** [meilisearch/meilisearch-react#4]
Hello 👋 

I've been using MeiliSearch-React and was able to use `react-instantsearch` along with `Highlight` API successfully 🎉 

However, I'm also trying to use the [Snippet API](https://www.algolia.com/doc/api-reference/widgets/snippet/react/), but the `_snippetResult` property seems to come back as `null`. I might be missing something though, but this is reproducible in the sandbox mentioned in the repository as well. I'm wondering if something extra needs to be done for the same.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/11358903/96591362-cd4b6780-1304-11eb-9841-5a7745803152.png">

FWIW: Algolia has an [`attributesToSnippet`](https://www.algolia.com/doc/api-reference/api-parameters/attributesToSnippet/) property, which I think determines what comes back in the snippetResult. Is there a similar option to that? I also don't see docs mentioning about Snippeting, so not entirely sure if Snippets are currently supported in Meili now ( I might be wrong about this 😅 ).

Thanks!

**Comment by curquiza** [comment]
Hello @Shriram-Balaji!

Thanks for using MeiliSearch and trying to integrate it into your react application 😁

There is indeed an equivalent to `snippet` in MeiliSearch that is called `crop`. See [this documentation](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#attributes-to-crop). But as you are using InstantSearch which belongs to Algolia, all the configuration in front end will be called `snippet`.

Here are the steps to add the snippetting:

- Add the snippetting in the `Configure` component:

```js
<Configure
    attributesToSnippet={['description:50']}
    snippetEllipsisText={"…"}
/>
```

(`50` is the number of characters, not words!)

- Add the `Snippet component`

```js
<Snippet attribute="description" hit={props.hit} />
```

This works for me.

Tell me if you still have the issue. Maybe do you work with an old [`instant-meilisearch`](https://github.com/meilisearch/instant-meilisearch) version? The crop/snippet has been added since the v0.2.0 and the latest is the v0.2.2.

If you still stuck, I will create a sandbox to show you what I succeed to get 🙂

**Comment by Shriram-Balaji** [comment]
@curquiza Thank You! The `Configure` was what I was missing. I was able to get it to work.

Quick question: Is there a simple way to hide an attribute Highlight / Snippet if it doesn't have anything matches at all? 

Say I have a document indexed like 

```json
{ 
 name: 'shriram',
 phone: 1234567890,
dob: 01/01/1960

}
```

and my searchQuery is `shriram`. Here the hit will only be on the `hit.name`, and I don't want to show the other two snippets.

**Comment by curquiza** [comment]
@Shriram-Balaji
What do you mean exactly by `I don't want to show the other two attribute snippets / highlights`?

When setting `attributesToHighligh` to `["name"]` (and with `q="shiram"`) you get this hit:

```json
{ 
    "name": "shriram",
    "phone": 1234567890,
    "dob": "01/01/1960",
    "_formatted": {
        "title": "<em>shiram</em>",
        "phone": 1234567890,
        "dob": "01/01/1960"
    }
}
``` 

Do you want to get the situation 1 or 2?

- situation 1:

```json
{ 
    "name": "shriram",
    "phone": 1234567890,
    "dob": "01/01/1960",
    "_formatted": {
        "title": "<em>shiram</em>",
    }
}
```

- situation 2:

```json
{ 
    "name": "shriram",
    "_formatted": {
        "title": "<em>shiram</em>",
    }
}
```

Unfortunately, situation 1 is not doable, but situation 2 is by setting `attributesToRetrieve` to `name` 🙂
See [these docs](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#attributes-to-retrieve)

**Comment by Shriram-Balaji** [comment]
@curquiza Basically, there are some fields in a search document that I want to show only if there's an actual text match to highlight.

It seems to me that I could just do a `.contains('em')` on the hit response, but that feels slightly messy.

**Comment by curquiza** [comment]
Ok I understand better now, and, unfortunately you cannot do that with MeiliSearch so far. 
Glad your fix works even if you are not really proud of it, I hope this would be useful for people looking for a solution! Thanks for your feedback then 😁

**Comment by vivekneem** [comment]
@curquiza , I am getting same issue with vue-instantsearch. In my case when I do add <AisConfigure/> component, meilisearch doesn't take any query parameters(It doesn't work). Both, <AisConfigure/> & <AisSnippet> components are not working for me with meili. Can you help me out or make any sandbox with vue?

**Comment by curquiza** [comment]
Hello @vivekneem!
We made a sandbox with Vue (that is accessible from the [`meilisearch-vue`](https://github.com/meilisearch/meilisearch-vue/) README -> https://codesandbox.io/s/ms-vue-is-1d6bi.
If you still have the issue,  can you open a new issue in https://github.com/meilisearch/meilisearch-vue/ or https://github.com/meilisearch/instant-meilisearch/?
Don't hesitate to detail your steps 😉

**Comment by vivekneem** [comment]
@curquiza , I have just gone through your codesandbox example. Whatever things you have used in an example are also working fine for me, but ais-snippet & ais-configure components are not working

**Comment by curquiza** [comment]
Can you open a new issue with the detailed steps please? We cannot help you if you don't describe what you are doing.
Here is the link to open a new issue: https://github.com/meilisearch/instant-meilisearch/issues/new

I'm also going to open an issue to improve the documentation of these packages 😉
