### ISSUE TITLE
Wrong get started instructions

### ISSUE THREAD

**Issue by kauly** [meilisearch/meilisearch-react#53]
There is a typo in the README, the `searchClient` must be destructed from the `instantMeiliSearch`, like this:

```js
const { searchClient } = instantMeiliSearch(
  'https://ms-adf78ae33284-106.lon.meilisearch.io',
  'a63da4928426f12639e19d62886f621130f3fa9ff3c7534c5d179f0f51c4f303'
);
``` 
Also the CodeSandbox is using  `react-instantsearch-dom` instead of `react-instantsearch`.

Related issue: https://github.com/meilisearch/meilisearch-js-plugins/issues/1268

**Comment by tshmieldev** [comment]
@kauly thank you you saved me

**Comment by curquiza** [comment]
Both problems are now fixed, in code sandbox and in the README. Sorry for the inconvenience and thanks a lot for the report
